### ISSUE TITLE
Make the entire character/group item clickable

### ISSUE THREAD

**Issue by timmyomahony** [callump5/Project-Comic#4]
At the moment, you have to click the actual name itself to change page. It might be easier to have the entire `<li>` element clickable. You could do this by having a small piece of javascript that listens for clicks on the `<li>` items and find the nearest `<a href=''>`. Something like:

```
// css
.tile {
  cursor: pointer;
  position: relative;

  // this makes the tile feel like a button when you click it
  &:active {
    top: 1px;
    left: 1px;
  }
}
```

```
// js (not 100% sure on the syntax here but this is the idea)
$(".tile").click(function() {
  window.location = $(this).find('a').attr('href');
});
```

**Comment by callump5** [comment]
Ah thanks this is pretty cool! 

not quite sure where to put the js tho, also would this still work with ng-click being on the a? or will i have to move that? although itll probably be changed after monday
